### ISSUE TITLE
Possible main OBS output (program) as source?

### ISSUE THREAD

**Issue by ASchneiderBR** [norihiro/obs-async-source-duplication#4]
Hello sir!

First of all, thank you for creating yet another incredible plugin. This is really powerful and very useful for so many reasons. The moment the visible main source bug is solved, I'll change from using Source Mirror (StreamFX) to your solution :)

I was wondering: do you think it would be possible to add the possibility of having the main output (program) as regular source? This is very useful since you can add your output to a scene, add effects like crop, rotate, change aspect ration and even send to another service using Exeldro's source record. Also, having the output audio track 1 or possibly all available tracks as a selectable audio source would be very powerful as well.

Thank you very much for your great work here :)

**Comment by norihiro** [comment]
> I was wondering: do you think it would be possible to add the possibility of having the main output (program) as regular source?

Especially use with the source-record plugin, previously I tried and there were some difficulties to send the main output.
It would require a little messy implementation... implemeting a virtual output, then forward it's video and audio to a source.
What is your use-case to send main output to another source? I'm wondering how many people need the feature.
I guess current working solution would be using NDI or Teleport (a free alternative to NDI, using mjpeg).

**Comment by ASchneiderBR** [comment]
Hello! Thanks for the reply. Yes, using NDI or virtual grabbing the output is the current solution but both are kind of unstable and uses more resources than it should. A couple of examples is to be able to output the same OBS sources and scenes for different output aspect ratios (using source record plugin). I could stream to a 16x9 aspect ratio (twitch, YT) using the main output and at the same time, add an Instagram scene, add the output as source, rotate it, add source record filter and output to Instagram's 9x16 aspect ratio. Another use case is to add the live output to a scene, add another information like chat messages, output this scene as a virtual cam then join in a meeting like zoom or teams as a very useful monitor/information screen for all participants. Having the audio main output, like track 1, would be great for creating macros using StreamerBot, for example, so you could heard only on your headset the exact audio main output that is going to the live stream (audio monitor plugin), so you can check if something is wrong or not. Thank you!

**Comment by norihiro** [comment]
Another plugin [obs-main-view-render](https://github.com/norihiro/obs-main-view-source) is started just now. [First release is here.](https://github.com/norihiro/obs-main-view-source/releases/tag/0.1.0)
This plugin provide the main view as a source.
If I understand correctly, Source Record provide the feature to select different track or specific audio source so that the main view (video of the program) without audio should be enough.

**Comment by ASchneiderBR** [comment]
Hello! Wow, thank you so much, I'll try it out and let you know ASAP. Have a great day!

**Comment by ASchneiderBR** [comment]
Amazing work mate, working great, even with transparency! Thank you very much sir!
